# Generated by Django 5.0.7 on 2024-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='property_images/default_image.jpg', upload_to='property_images/'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
